/**
 *  Script responsible for creating all the tables, functions and stored procedures
 *  TODO: Remove hardcoded data
 */

create table public."Scoreboards" (
  id bigint generated by default as identity not null,
  name character varying not null,
  constraint Scoreboards_pkey primary key (id)
) TABLESPACE pg_default;

create table public."ScoreboardsScores" (
  id bigint generated by default as identity not null,
  scoreboard_id bigint not null,
  position smallint not null,
  score smallint not null,
  constraint ScoreboardsScores_pkey primary key (id),
  constraint ScoreboardsScores_scoreboard_id_fkey foreign KEY (scoreboard_id) references "Scoreboards" (id)
) TABLESPACE pg_default;

create table public."Seasons" (
  id bigint generated by default as identity not null,
  name character varying null,
  constraint Seasons_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Teams" (
  id smallint generated by default as identity not null,
  name character varying not null,
  color character varying null,
  constraint Teams_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Drivers" (
  id smallint generated by default as identity not null,
  name character varying not null,
  team_id smallint null,
  constraint Drivers_pkey primary key (id),
  constraint Drivers_team_id_fkey foreign KEY (team_id) references "Teams" (id) on update RESTRICT
) TABLESPACE pg_default;

create table public."Races" (
  id bigint generated by default as identity not null,
  season_id bigint not null,
  name character varying not null,
  scoreboard_id bigint null,
  best_lap_scoreboard_id bigint null,
  race_date timestamp without time zone null default now(),
  constraint Races_pkey primary key (id),
  constraint Races_best_lap_scoreboard_id_fkey foreign KEY (best_lap_scoreboard_id) references "Scoreboards" (id),
  constraint Races_scoreboard_id_fkey foreign KEY (scoreboard_id) references "Scoreboards" (id),
  constraint Races_season_id_fkey foreign KEY (season_id) references "Seasons" (id)
) TABLESPACE pg_default;

create table public."RacesResults" (
  race_id bigint not null,
  driver_id smallint not null,
  rank smallint null,
  laps smallint null,
  avg_time double precision null,
  best_lap double precision null,
  constraint RacesResults_pkey primary key (race_id, driver_id),
  constraint RacesResults_driver_id_fkey foreign KEY (driver_id) references "Drivers" (id),
  constraint RacesResults_race_id_fkey foreign KEY (race_id) references "Races" (id)
) TABLESPACE pg_default;

create table public."Standings" (
  season_id bigint not null,
  driver_id smallint not null,
  points_from_race bigint not null default '0'::bigint,
  points_from_bestlap bigint not null default '0'::bigint,
  points bigint not null default '0'::bigint,
  rank smallint null,
  constraint Standings_pkey primary key (season_id, driver_id),
  constraint Standings_driver_id_fkey foreign KEY (driver_id) references "Drivers" (id) on update RESTRICT,
  constraint Standings_season_id_fkey foreign KEY (season_id) references "Seasons" (id)
) TABLESPACE pg_default;

create or replace procedure updateStandings(p_season_id int)
language plpgsql
as $$
declare
begin
  DELETE FROM "Standings" WHERE "season_id" = p_season_id;

  INSERT INTO "Standings" (rank, season_id, driver_id, points_from_race, points_from_bestlap, points) 
  (
    SELECT row_number() OVER(ORDER BY SUM(score1.score) + SUM(score2.score) DESC) AS rank, p_season_id AS season_id, rr.driver_id AS driver_id, SUM(score1.score) AS points_from_race, SUM(score2.score) AS points_from_bestlap, SUM(score1.score) + SUM(score2.score) AS points
    FROM "RacesResults" rr
    JOIN "Races" r ON rr.race_id = r.id
    JOIN "ScoreboardsScores" score1 ON r.scoreboard_id = score1.scoreboard_id AND score1.position = rr.rank
    JOIN (SELECT row_number() OVER(PARTITION BY "race_id") AS best_lap_rank, race_id, driver_id FROM "RacesResults" ORDER BY best_lap) AS rr2 
    ON rr.race_id = rr2.race_id AND rr.driver_id = rr2.driver_id
    JOIN "ScoreboardsScores" score2 ON r.best_lap_scoreboard_id = score2.scoreboard_id AND score2.position = rr2.best_lap_rank
    WHERE r.season_id = p_season_id
    GROUP BY rr.driver_id
    ORDER BY "points" DESC
  );
end; $$

-- Data
INSERT INTO "Scoreboards" ("name") VALUES ('Main');

INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 1, 8);
INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 2, 6);
INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 3, 5);
INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 4, 4);
INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 5, 3);
INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 6, 2);
INSERT INTO "ScoreboardsScores" ("scoreboard_id", "position", "score") VALUES (1, 7, 1);

INSERT INTO "Seasons" ("name") VALUES ('2025');

INSERT INTO "Teams" ("name", "color") VALUES ('Red Bull', '#3672c6');
INSERT INTO "Teams" ("name", "color") VALUES ('McLaren', '#ff8000');
INSERT INTO "Teams" ("name", "color") VALUES ('Ferrari', '#e8002e');

INSERT INTO "Drivers" ("name", "team_id") VALUES ('André', 1);
INSERT INTO "Drivers" ("name", "team_id") VALUES ('Ribeiro', 2);
INSERT INTO "Drivers" ("name", "team_id") VALUES ('Alex', 3);
INSERT INTO "Drivers" ("name", "team_id") VALUES ('Dany', 3);
INSERT INTO "Drivers" ("name", "team_id") VALUES ('Bruno', 1);
INSERT INTO "Drivers" ("name", "team_id") VALUES ('Ruben', 2);

INSERT INTO "Races" ("season_id", "name", "scoreboard_id", "best_lap_scoreboard_id", "race_date") VALUES (1, 'GP Fafe Indoor', 1, 1, now());
INSERT INTO "RacesResults" ("race_id", "driver_id", "rank", "laps", "avg_time", "best_lap") VALUES (1, 1, 1, 39, 30.354, 26.590);
INSERT INTO "RacesResults" ("race_id", "driver_id", "rank", "laps", "avg_time", "best_lap") VALUES (1, 2, 3, 37, 31.797, 26.815);
INSERT INTO "RacesResults" ("race_id", "driver_id", "rank", "laps", "avg_time", "best_lap") VALUES (1, 3, 4, 37, 32.033, 27.094);
INSERT INTO "RacesResults" ("race_id", "driver_id", "rank", "laps", "avg_time", "best_lap") VALUES (1, 4, 6, 35, 33.445, 27.147);
INSERT INTO "RacesResults" ("race_id", "driver_id", "rank", "laps", "avg_time", "best_lap") VALUES (1, 5, 5, 35, 33.425, 27.175);
INSERT INTO "RacesResults" ("race_id", "driver_id", "rank", "laps", "avg_time", "best_lap") VALUES (1, 6, 2, 38, 31.061, 27.436);